#!/bin/bash
# Stamps BuildMetadata.xcconfig with the short git commit of the checkout being
# built so Settings can show it next to the version number. Runs as the
# TaskMenu scheme's build pre-action; CI also runs it explicitly before
# archiving. Never fails the build: a missing git checkout leaves the hash
# empty and the app falls back to "dev".
set -euo pipefail

repo_root="${1:-$(pwd)}"
metadata_path="${repo_root}/BuildMetadata.xcconfig"

commit_hash="$(/usr/bin/git -C "${repo_root}" rev-parse --short HEAD 2>/dev/null || true)"

{
  printf '// Generated by scripts/stamp_build_metadata.sh. Not tracked in git.\n'
  printf 'GIT_COMMIT_HASH = %s\n' "${commit_hash}"
} > "${metadata_path}"
